name: ci
on:
  push:
    paths:
      - 'db/**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push - web
        uses: docker/build-push-action@v2
        with:
          context: ./web
          file: ./web/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/wordsmith_web:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/wordsmith_web:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/wordsmith_web:buildcache,mode=max
      -
        name: Build and push - words
        uses: docker/build-push-action@v2
        with:
          context: ./words
          file: ./words/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/wordsmith_words:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/wordsmith_words:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/wordsmith_words:buildcache,mode=max
      -
        name: Build and push - db
        uses: docker/build-push-action@v2
        with:
          context: ./db
          file: ./db/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/wordsmith_db:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/wordsmith_db:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/wordsmith_db:buildcache,mode=max