name: ci
on:
  push:
    branches:
      - 'github-action'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push - web
        uses: docker/build-push-action@v2
        with:
          context: ./web
          file: ./web/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/wordsmith_web:latest
      -
        name: Build and push - words
        uses: docker/build-push-action@v2
        with:
          context: ./words
          file: ./words/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/wordsmith_words:latest
      -
        name: Build and push - db
        uses: docker/build-push-action@v2
        with:
          context: ./db
          file: ./db/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/wordsmith_db:latest